os:
    - linux
matrix:
    include:
        -
            dotnet: 5.0
            install: ['dotnet restore']
            language: csharp
            mono: none
            script: ['dotnet build', 'dotnet test Core.Tests/Core.Tests.csproj']
            solution: MSPC.sln
