os:
  - linux
matrix:
  include:
    - language: csharp
      solution: MSPC.sln
      mono: none
      dotnet: 2.0.3
      install:
        - dotnet restore
      script:
      - dotnet build
      - dotnet test Core.Tests/Core.Tests.csproj
      
    - language: node_js
      node_js:
        - '8'
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
