os:
    - linux
matrix:
    include:
        -
            dotnet: 3.0
            install: ['dotnet restore']
            language: csharp
            mono: none
            script: ['dotnet build', 'dotnet test Core.Tests/Core.Tests.csproj']
            solution: MSPC.sln
        -
            cache: {yarn: true}
            language: node_js
            node_js: ['8']
            script: ['git config --global user.name "${GH_NAME}"', 'git config --global user.email "${GH_EMAIL}"', 'echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc', 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages; fi']
