# Common configuration for all branches
version: '3.0.{build}'
image: Visual Studio 2017

init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - dotnet restore
build:
  verbosity: minimal
clone_depth: 1

build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"mspc" /o:"genometric" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.analysis.mode=preview"
  - MSBuild.exe /t:Rebuild
  - MSBuild.SonarQube.Runner.exe end 

test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore Core.Tests\Core.Tests.csproj --verbosity m
  - cmd: dotnet test Core.Tests\Core.Tests.csproj
  - ps: cd Core.Tests
  - OpenCover.Console.exe -register:"user" -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"xunit -noshadow" -filter:"+[*]* -[Core.Tests*]*" -oldStyle -output:".\mspc_coverage.xml"
  - ps: cd ..
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
on_finish :
  # any cleanup in here

deploy: off

# override common configuration for each branch
for:

# override settings for `master` branch
-
  branches:
    only:
      - master

  configuration: Release
  
  environment:
    sonartoken:
      secure: lv4kUp8/VoGY/BYpOlov5AUt5ZCzXIIjSdiN+xHlX/kF9lfG1r7ibe3NB3/voIn5
    codecovtoken:
      secure: dKCzX4gNxZYO3rxHOCnB+PzxeJIZZTsQLC5rczdcp/egmD1IN9u+b8srqxrj65jy
  
  build_script:
    - choco install "msbuild-sonarqube-runner" -y
    - MSBuild.SonarQube.Runner.exe begin /k:"mspc" /o:"genometric" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%sonartoken%"
    - MSBuild.exe /t:Rebuild
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%sonartoken%"
    
  after_test:
    - ps: |
        $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
        Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
        bash codecov.sh -f "Core.Tests/mspc_coverage.xml" -t $env:codecovtoken
    - MSBuild.SonarQube.Runner.exe begin /k:"mspc" /o:"genometric" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%sonartoken%" /d:sonar.cs.opencover.reportsPaths="\Core.Tests\mspc_coverage.xml"
    - MSBuild.exe /t:Rebuild
    - ps: cd Core.Tests
    - OpenCover.Console.exe -register:"user" -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"xunit -noshadow" -filter:"+[*]*" -oldStyle -output:"mspc_coverage.xml"
    - ps: cd ..
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%sonartoken%"
  
  artifacts: 
    - path: MSPC/bin/Release/Genometric.MSPC*.nupkg  
      name: MSPC
    
#  deploy:
#    provider: NuGet
#    api_key:
#      secure: 0ubG+Z4SGof+VEFEQD4Gm5JIb4L6+lMq3pnRfUhim5RLUw+JaC5Qx9dBMWZ9JRuD
#    skip_symbols: false

# override settings for `dev*` branches
-
  branches:
    only:
      - /dev*/
      
  configuration: Debug
  
  after_test:
    - ps: |
        $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
        Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
        bash codecov.sh -f "Core.Tests/mspc_coverage.xml"
