version: '4.0.{build}'
image: 'Visual Studio 2019'
init:
    -
        cmd: 'git config --global core.autocrlf true'
install:
    - 'nuget restore'
    - 'dotnet restore'
    - 'choco install opencover.portable'
    - 'choco install codecov'
before_build:
    - 'nuget restore'
    - 'choco install opencover.portable'
    - 'choco install codecov'
build:
    verbosity: minimal
clone_depth: 1
test_script:
    -
        cmd: 'dotnet restore Core.Tests\Core.Tests.csproj --verbosity m'
    -
        cmd: 'dotnet test Core.Tests\Core.Tests.csproj'
    -
        cmd: 'cd Core.Tests'
    - 'OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[*]* -[Core.Tests*]*" -output:".\mspc_coverage.xml" -oldstyle'
# on_finish: any clean up code here
deploy: off
for:
    -
        branches:
            only: [master]
        configuration: Release
        environment:
            codecovtoken: {secure: dKCzX4gNxZYO3rxHOCnB+PzxeJIZZTsQLC5rczdcp/egmD1IN9u+b8srqxrj65jy}
        build_script:
            - 'MSBuild.exe /t:Rebuild'
        after_test:
            - {ps: "$env:PATH = 'C:\\msys64\\usr\\bin;' + $env:PATH\nInvoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh\nbash codecov.sh -f \"mspc_coverage.xml\"\n"}
            - 'MSBuild.exe /t:Rebuild'
            - 'OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[*]* -[Core.Tests*]*" -output:"mspc_coverage.xml" -oldstyle'
            - {ps: 'cd ..'}
        artifacts:
            - {path: 'Core/bin/Release/Genometric.MSPC.Core*.nupkg', name: MSPC}
        deploy:
            provider: NuGet
            api_key: {secure: R9BDT6tjyjrRf/SNqhrjz3Bju8vUGEZ05qG6UAIF7Zmam2Wk8wjZgDMVyzRvY8Ae}
            skip_symbols: false
    -
        branches:
            only: ['/dev*/']
        configuration: Debug
        after_test:
            - {ps: "$env:PATH = 'C:\\msys64\\usr\\bin;' + $env:PATH\nInvoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh\nbash codecov.sh -f \"mspc_coverage.xml\"\n"}
