name: SonarCloud

on:
  push:
    branches: [ dev, main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarqube:
    # To skip running this on PRs from forks as it will not provide token for such PRs and they will fail. 
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io"
